// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using website_backend.DbContexts;

#nullable disable

namespace website_backend.Migrations
{
    [DbContext(typeof(WebsiteContext))]
    partial class WebsiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("website_backend.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "this is better than anything I could ever do",
                            PostId = 1,
                            Title = "Really cool!"
                        },
                        new
                        {
                            Id = 2,
                            Body = "lorem ipsum is a sample text who cares tho",
                            PostId = 1,
                            Title = "Lorem "
                        },
                        new
                        {
                            Id = 3,
                            Body = "lorem ipsum is a sample text who cares tho",
                            PostId = 1,
                            Title = "Lorem Log 3"
                        },
                        new
                        {
                            Id = 4,
                            Body = "this is dev log one",
                            PostId = 2,
                            Title = "Really cool!"
                        },
                        new
                        {
                            Id = 5,
                            Body = "this is dev log two",
                            PostId = 2,
                            Title = "Dev Lorem 2"
                        },
                        new
                        {
                            Id = 6,
                            Body = "lorem ipsum is a sample text who cares tho",
                            PostId = 2,
                            Title = "Lorem Log 3"
                        },
                        new
                        {
                            Id = 7,
                            Body = "So this is how you do it!",
                            PostId = 3,
                            Title = "Really cool!"
                        },
                        new
                        {
                            Id = 8,
                            Body = "I could do way better",
                            PostId = 3,
                            Title = "Kinda sucks"
                        },
                        new
                        {
                            Id = 9,
                            Body = "lorem ipsum is a sample text who cares tho",
                            PostId = 3,
                            Title = "Lorem ipsum"
                        });
                });

            modelBuilder.Entity("website_backend.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "this is dev log one",
                            Title = "Dev Log 1"
                        },
                        new
                        {
                            Id = 2,
                            Body = "this is dev log two",
                            Title = "Dev Log 2"
                        },
                        new
                        {
                            Id = 3,
                            Body = "this is dev log three",
                            Title = "Dev Log 3"
                        });
                });

            modelBuilder.Entity("website_backend.Entities.Comment", b =>
                {
                    b.HasOne("website_backend.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("website_backend.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
